DROP TABLE IF EXISTS `#__downfiles`;
DROP TABLE IF EXISTS `#__downfiles_stat`;

CREATE TABLE IF NOT EXISTS `#__downfiles`(
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`filename` VARCHAR(1024) NOT NULL,
	`file_desc` VARCHAR(150) NOT NULL,
	`published` tinyint(4) DEFAULT NULL,
	PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#__downfiles_stat`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`filename_id` INT(11) NOT NULL,
	`date` DATETIME NOT NULL,
	`ip_addr` VARCHAR(40) NOT NULL,
	PRIMARY KEY (`id`)	
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;